### ISSUE TITLE
After replacing all msgpack implementations with loop fields, the execution speed slowed down considerably

### ISSUE THREAD

**Issue by halajohn** [TEN-framework/ten_framework.bak#228]

**Comment by sunxilin** [comment]
When I noticed the slowdown in performance, I did not conduct a proper control experiment. The slow execution at that time could have been due to the machine running other programs or other reasons. Later, I conducted a control experiment again, running 200 smoke tests, and the execution times for both were nearly the same.

**Comment by sunxilin** [comment]
![企业微信截图_0a773eef-e8a8-4908-bd73-dcfd489a12f3](https://github.com/user-attachments/assets/1dbf9e5d-5023-4029-a623-c106ee53fdf6)
Before replacing the implementation of msgpack, the total time taken to run the smoke tests was 55,979 ms.

![企业微信截图_e03c432f-fc6f-4879-8f5f-aea4efeaeff7](https://github.com/user-attachments/assets/8a8f2451-65eb-47db-b4ac-ae28f49d5cac)
After replacing the implementation of msgpack with loop, the total time taken was 55,925 ms.
